redis_ambassador:
    image: svendowideit/ambassador
    container_name: redis-ambassador
    environment:
        - REDIS_PORT_6379_TCP=tcp://rohan-redis.cloudapp.net:6379
    ports:
        - "6379:6379"

redis-cli:
    image: redis
    container_name: my_redis_cli
    links:
        - redis_ambassador:redis
    expose: [6379]
    command: /bin/bash -c "redis-cli -h $REDIS_PORT_6379_TCP_ADDR"
