redis:
    image: redis
    container_name: docker-redis

redis_ambassador:
    image: svendowideit/ambassador
    container_name: redis-ambassador
    links:
        - redis
    ports:
        - "6379:6379"
