from updated-ubuntu
RUN apt-get install -y socat
COPY scripts/create_file.sh scripts/create_file.sh
COPY scripts/serve_file_on_port.sh scripts/serve_file_on_port.sh
COPY scripts/create_and_serve.sh scripts/create_and_serve.sh
